name: Compilación Práctica 2
on:
  push:
    branches: 
    - master
    - prac2
  workflow_dispatch:
    
jobs:
  compilar_todo:
    #runs-on: ubuntu-16.04
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Compilar todo
        run: make debug
        
